//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHETEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACHETEUR()
        {
            this.FICHE_DE_SOUHAITS = new HashSet<FICHE_DE_SOUHAITS>();
        }
    
        public short IDACHETEUR { get; set; }
        public byte IDCOMMERCIAL { get; set; }
        public short IDVILLE { get; set; }
        public string NOM_ACHETEUR { get; set; }
        public string PRENOM_ACHETEUR { get; set; }
        public string ADRESSE { get; set; }
        public string EMAIL { get; set; }
        public int TÉLÉPHONE { get; set; }
    
        public virtual COMMERCIAL COMMERCIAL { get; set; }
        public virtual VILLE VILLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHE_DE_SOUHAITS> FICHE_DE_SOUHAITS { get; set; }
    }
}
