//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDV
    {
        public short IDRDV { get; set; }
        public short IDVISITE { get; set; }
    
        public virtual PROPOSITION_VISITE PROPOSITION_VISITE { get; set; }
    }
}
