//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIEN()
        {
            this.PROPOSITION_VISITE = new HashSet<PROPOSITION_VISITE>();
        }
    
        public short IDBIEN { get; set; }
        public int IDVILLE { get; set; }
        public short IDVENDEUR { get; set; }
        public int SURFACE_HABITABLE { get; set; }
        public int SURFACE_PARCELLE { get; set; }
        public int NB_PIÈCES { get; set; }
        public int NB_CHAMBRES { get; set; }
        public int NB_SALLEDEBAIN { get; set; }
        public bool GARAGE { get; set; }
        public bool CAVE { get; set; }
        public int PRIX_SOUHAITÉ { get; set; }
        public string ADRESSE_BIEN { get; set; }
        public int CODE_POSTAL { get; set; }
        public System.DateTime DATE_MISEENVENTE { get; set; }
        public string STATUT { get; set; }
        public string ZONE_DE_SAISIE { get; set; }
        public short NB_VISITES { get; set; }
    
        public virtual VENDEUR VENDEUR { get; set; }
        public virtual VILLE VILLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSITION_VISITE> PROPOSITION_VISITE { get; set; }
    }
}
