//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMERCIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMERCIAL()
        {
            this.ACHETEUR = new HashSet<ACHETEUR>();
        }
    
        public short IDCOMMERCIAL { get; set; }
        public string NOM_COMMERCIAL { get; set; }
        public string PRENOM_COMMERCIAL { get; set; }
        public int TÉLÉPHONE_FIXE_PRO { get; set; }
        public int TÉLÉPHONE_MOBILE_PRO { get; set; }
        public Nullable<int> TÉLÉPHONE_PERSONNEL { get; set; }
        public string EMAIL { get; set; }
        public string STATUT_COMMERCIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHETEUR> ACHETEUR { get; set; }
    }
}
