//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnfinEntities2 : DbContext
    {
        public EnfinEntities2()
            : base("name=EnfinEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACHETEUR> ACHETEUR { get; set; }
        public virtual DbSet<BIEN> BIEN { get; set; }
        public virtual DbSet<COMMERCIAL> COMMERCIAL { get; set; }
        public virtual DbSet<FICHE_DE_SOUHAITS> FICHE_DE_SOUHAITS { get; set; }
        public virtual DbSet<PROPOSITION_VISITE> PROPOSITION_VISITE { get; set; }
        public virtual DbSet<RDV> RDV { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VENDEUR> VENDEUR { get; set; }
        public virtual DbSet<VILLE> VILLE { get; set; }
    }
}
